Login
MatejaMitic/cocktails9 pull request #1
Opened 2024-11-27 14:04 UTC by MatejaMitic

2024-11-28 12:13 UTC, nm-levi9 requested changes
Clean. Simple. Maybe too simple?

I left a few comments for a minor code improvements 🙂 beside comments I left, I would like to share this nifty little trick to keep your code formatted:
Before committing the code, select all code (`cmd+A`) while inside the .swift file, and press this magic combination `cmd+i`. This will make it formatted per swift code convention.

2024-11-28 12:13 UTC, nm-levi9 commented on Cocktails9/Cocktails9/Login.swift
> +    @State private var isLoggedIn: Bool = false
you don't need this Bool. I see it's only used in one `func` down below, so it can be that `func`'s local `var` (or `let`)

2024-11-28 12:13 UTC, nm-levi9 commented on Cocktails9/Cocktails9/Login.swift
> +            currentImageName = (currentImageName == "cocktailP1") ? "cocktailP2" : "cocktailP1"
I think you're checking the wrong `Bool` here.

2024-11-28 16:48 UTC, dunja-maksimovic-levi9-com commented on Cocktails9/Cocktails9/Login.swift
> +struct Login: View {
It would be more precise to call this "LoginView"

2024-11-28 16:48 UTC, dunja-maksimovic-levi9-com commented on Cocktails9/Cocktails9/Login.swift
> +                SecureField("Password", text: $password)
Nicely done :)

2024-12-03 12:38 UTC, nm-levi9 approved these changes
Good to go. I'll just note once again: It would be nice to have some UI complications. I'm a minimalist myself, but I advise you to take a look at various app designs/themes and apply some of them. Using system elements for DEMO is rarely only a good practice for PoC projects when you don't have time to build complex UI.

2024-12-04 12:40 UTC, merged